[package]
name = "acmumn-auth"
version = "0.1.0"
authors = ["Nathan Ringo <remexre@gmail.com>"]

[dependencies]
failure = "0.1.2"
hyper = "0.12.8"
log = "0.4.4"
serde = "1.0.75"
serde_derive = "1.0.75"
serde_json = "1.0.26"
